using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using myAntlr.astnodes.statements;

namespace myAntlr.parsing
{
    // To avoid conflict of FunctionParser.cs in obj folder generated by Antlr.
    // Change this class name to FunctionParserInParsing.

    class FunctionParserInParsing
    {
        ANTLRParserDriver parser;

        public FunctionParserInParsing()
        {
            parser = new ANTLRFunctionParserDriver();
        }

        public void parseAndWalkString(String input)
        {
            parser.parseAndWalkString(input);
        }

        public CompoundStatement getResult()
        {
            // The result is what's left on the stack in the end
            return parser.getResult();
        }
    }
}
